phantomjs_test: Ignore 'undefined' behavior in PhantomJS 1.9.8
Ignore PhantomJSRPCError: TypeError: 'undefined' is not a function
introduced in PhantomJS 1.9.8